/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test4bit(D_IN, CLK, EN, D_OUT);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  input CLK;
  input [3:0] D_IN;
  output [3:0] D_OUT;
  input EN;
  sky130_fd_sc_hd__mux2_1 _04_ (
    .A0(D_OUT[1]),
    .A1(D_IN[1]),
    .S(EN),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _05_ (
    .A0(D_OUT[2]),
    .A1(D_IN[2]),
    .S(EN),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _06_ (
    .A0(D_OUT[3]),
    .A1(D_IN[3]),
    .S(EN),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _07_ (
    .A0(D_OUT[0]),
    .A1(D_IN[0]),
    .S(EN),
    .X(_00_)
  );
  sky130_fd_sc_hd__dfxtp_1 _08_ (
    .CLK(CLK),
    .D(_00_),
    .Q(D_OUT[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _09_ (
    .CLK(CLK),
    .D(_01_),
    .Q(D_OUT[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _10_ (
    .CLK(CLK),
    .D(_02_),
    .Q(D_OUT[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _11_ (
    .CLK(CLK),
    .D(_03_),
    .Q(D_OUT[3])
  );
endmodule
