/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test1(x, y, s, clk, r);
  wire _0_;
  wire _1_;
  wire _2_;
  input clk;
  output r;
  input s;
  input x;
  input y;
  sky130_fd_sc_hd__xnor2_1 _3_ (
    .A(y),
    .B(x),
    .Y(_1_)
  );
  sky130_fd_sc_hd__nor2_1 _4_ (
    .A(r),
    .B(s),
    .Y(_2_)
  );
  sky130_fd_sc_hd__a21oi_1 _5_ (
    .A1(s),
    .A2(_1_),
    .B1(_2_),
    .Y(_0_)
  );
  sky130_fd_sc_hd__dfxtp_1 _6_ (
    .CLK(clk),
    .D(_0_),
    .Q(r)
  );
endmodule
