/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test32bit(D_IN, CLK, EN, D_OUT);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  input CLK;
  input [31:0] D_IN;
  output [31:0] D_OUT;
  input EN;
  sky130_fd_sc_hd__mux2_1 _32_ (
    .A0(D_OUT[1]),
    .A1(D_IN[1]),
    .S(EN),
    .X(_11_)
  );
  sky130_fd_sc_hd__mux2_1 _33_ (
    .A0(D_OUT[2]),
    .A1(D_IN[2]),
    .S(EN),
    .X(_22_)
  );
  sky130_fd_sc_hd__mux2_1 _34_ (
    .A0(D_OUT[3]),
    .A1(D_IN[3]),
    .S(EN),
    .X(_25_)
  );
  sky130_fd_sc_hd__mux2_1 _35_ (
    .A0(D_OUT[4]),
    .A1(D_IN[4]),
    .S(EN),
    .X(_26_)
  );
  sky130_fd_sc_hd__mux2_1 _36_ (
    .A0(D_OUT[5]),
    .A1(D_IN[5]),
    .S(EN),
    .X(_27_)
  );
  sky130_fd_sc_hd__mux2_1 _37_ (
    .A0(D_OUT[6]),
    .A1(D_IN[6]),
    .S(EN),
    .X(_28_)
  );
  sky130_fd_sc_hd__mux2_1 _38_ (
    .A0(D_OUT[7]),
    .A1(D_IN[7]),
    .S(EN),
    .X(_29_)
  );
  sky130_fd_sc_hd__mux2_1 _39_ (
    .A0(D_OUT[8]),
    .A1(D_IN[8]),
    .S(EN),
    .X(_30_)
  );
  sky130_fd_sc_hd__mux2_1 _40_ (
    .A0(D_OUT[9]),
    .A1(D_IN[9]),
    .S(EN),
    .X(_31_)
  );
  sky130_fd_sc_hd__mux2_1 _41_ (
    .A0(D_OUT[10]),
    .A1(D_IN[10]),
    .S(EN),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _42_ (
    .A0(D_OUT[11]),
    .A1(D_IN[11]),
    .S(EN),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _43_ (
    .A0(D_OUT[12]),
    .A1(D_IN[12]),
    .S(EN),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _44_ (
    .A0(D_OUT[13]),
    .A1(D_IN[13]),
    .S(EN),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux2_1 _45_ (
    .A0(D_OUT[14]),
    .A1(D_IN[14]),
    .S(EN),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_1 _46_ (
    .A0(D_OUT[15]),
    .A1(D_IN[15]),
    .S(EN),
    .X(_06_)
  );
  sky130_fd_sc_hd__mux2_1 _47_ (
    .A0(D_OUT[16]),
    .A1(D_IN[16]),
    .S(EN),
    .X(_07_)
  );
  sky130_fd_sc_hd__mux2_1 _48_ (
    .A0(D_OUT[17]),
    .A1(D_IN[17]),
    .S(EN),
    .X(_08_)
  );
  sky130_fd_sc_hd__mux2_1 _49_ (
    .A0(D_OUT[18]),
    .A1(D_IN[18]),
    .S(EN),
    .X(_09_)
  );
  sky130_fd_sc_hd__mux2_1 _50_ (
    .A0(D_OUT[19]),
    .A1(D_IN[19]),
    .S(EN),
    .X(_10_)
  );
  sky130_fd_sc_hd__mux2_1 _51_ (
    .A0(D_OUT[20]),
    .A1(D_IN[20]),
    .S(EN),
    .X(_12_)
  );
  sky130_fd_sc_hd__mux2_1 _52_ (
    .A0(D_OUT[21]),
    .A1(D_IN[21]),
    .S(EN),
    .X(_13_)
  );
  sky130_fd_sc_hd__mux2_1 _53_ (
    .A0(D_OUT[22]),
    .A1(D_IN[22]),
    .S(EN),
    .X(_14_)
  );
  sky130_fd_sc_hd__mux2_1 _54_ (
    .A0(D_OUT[23]),
    .A1(D_IN[23]),
    .S(EN),
    .X(_15_)
  );
  sky130_fd_sc_hd__mux2_1 _55_ (
    .A0(D_OUT[24]),
    .A1(D_IN[24]),
    .S(EN),
    .X(_16_)
  );
  sky130_fd_sc_hd__mux2_1 _56_ (
    .A0(D_OUT[25]),
    .A1(D_IN[25]),
    .S(EN),
    .X(_17_)
  );
  sky130_fd_sc_hd__mux2_1 _57_ (
    .A0(D_OUT[26]),
    .A1(D_IN[26]),
    .S(EN),
    .X(_18_)
  );
  sky130_fd_sc_hd__mux2_1 _58_ (
    .A0(D_OUT[27]),
    .A1(D_IN[27]),
    .S(EN),
    .X(_19_)
  );
  sky130_fd_sc_hd__mux2_1 _59_ (
    .A0(D_OUT[28]),
    .A1(D_IN[28]),
    .S(EN),
    .X(_20_)
  );
  sky130_fd_sc_hd__mux2_1 _60_ (
    .A0(D_OUT[29]),
    .A1(D_IN[29]),
    .S(EN),
    .X(_21_)
  );
  sky130_fd_sc_hd__mux2_1 _61_ (
    .A0(D_OUT[30]),
    .A1(D_IN[30]),
    .S(EN),
    .X(_23_)
  );
  sky130_fd_sc_hd__mux2_1 _62_ (
    .A0(D_OUT[31]),
    .A1(D_IN[31]),
    .S(EN),
    .X(_24_)
  );
  sky130_fd_sc_hd__mux2_1 _63_ (
    .A0(D_OUT[0]),
    .A1(D_IN[0]),
    .S(EN),
    .X(_00_)
  );
  sky130_fd_sc_hd__dfxtp_1 _64_ (
    .CLK(CLK),
    .D(_10_),
    .Q(D_OUT[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _65_ (
    .CLK(CLK),
    .D(_12_),
    .Q(D_OUT[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _66_ (
    .CLK(CLK),
    .D(_13_),
    .Q(D_OUT[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _67_ (
    .CLK(CLK),
    .D(_14_),
    .Q(D_OUT[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _68_ (
    .CLK(CLK),
    .D(_15_),
    .Q(D_OUT[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _69_ (
    .CLK(CLK),
    .D(_16_),
    .Q(D_OUT[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _70_ (
    .CLK(CLK),
    .D(_17_),
    .Q(D_OUT[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _71_ (
    .CLK(CLK),
    .D(_18_),
    .Q(D_OUT[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _72_ (
    .CLK(CLK),
    .D(_19_),
    .Q(D_OUT[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _73_ (
    .CLK(CLK),
    .D(_20_),
    .Q(D_OUT[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _74_ (
    .CLK(CLK),
    .D(_21_),
    .Q(D_OUT[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _75_ (
    .CLK(CLK),
    .D(_23_),
    .Q(D_OUT[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _76_ (
    .CLK(CLK),
    .D(_24_),
    .Q(D_OUT[31])
  );
  sky130_fd_sc_hd__dfxtp_1 _77_ (
    .CLK(CLK),
    .D(_00_),
    .Q(D_OUT[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _78_ (
    .CLK(CLK),
    .D(_11_),
    .Q(D_OUT[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _79_ (
    .CLK(CLK),
    .D(_22_),
    .Q(D_OUT[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _80_ (
    .CLK(CLK),
    .D(_25_),
    .Q(D_OUT[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _81_ (
    .CLK(CLK),
    .D(_26_),
    .Q(D_OUT[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _82_ (
    .CLK(CLK),
    .D(_27_),
    .Q(D_OUT[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _83_ (
    .CLK(CLK),
    .D(_28_),
    .Q(D_OUT[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _84_ (
    .CLK(CLK),
    .D(_29_),
    .Q(D_OUT[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _85_ (
    .CLK(CLK),
    .D(_30_),
    .Q(D_OUT[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _86_ (
    .CLK(CLK),
    .D(_31_),
    .Q(D_OUT[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _87_ (
    .CLK(CLK),
    .D(_01_),
    .Q(D_OUT[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _88_ (
    .CLK(CLK),
    .D(_02_),
    .Q(D_OUT[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _89_ (
    .CLK(CLK),
    .D(_03_),
    .Q(D_OUT[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _90_ (
    .CLK(CLK),
    .D(_04_),
    .Q(D_OUT[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _91_ (
    .CLK(CLK),
    .D(_05_),
    .Q(D_OUT[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _92_ (
    .CLK(CLK),
    .D(_06_),
    .Q(D_OUT[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _93_ (
    .CLK(CLK),
    .D(_07_),
    .Q(D_OUT[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _94_ (
    .CLK(CLK),
    .D(_08_),
    .Q(D_OUT[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _95_ (
    .CLK(CLK),
    .D(_09_),
    .Q(D_OUT[18])
  );
endmodule
