/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test4(x, s, clk, r);
  wire _0_;
  wire _1_;
  input clk;
  output r;
  input s;
  input x;
  sky130_fd_sc_hd__nor2_1 _2_ (
    .A(r),
    .B(s),
    .Y(_1_)
  );
  sky130_fd_sc_hd__a21oi_1 _3_ (
    .A1(s),
    .A2(x),
    .B1(_1_),
    .Y(_0_)
  );
  sky130_fd_sc_hd__dfxtp_1 _4_ (
    .CLK(clk),
    .D(_0_),
    .Q(r)
  );
endmodule
